### ISSUE TITLE
DeepLinking to Apps which are not Installed yet?

### ISSUE THREAD

**Issue by confile** [hoko/hoko-ios#2]
Is it possible to DeepLink to Apps which are not Installed yet?

**Comment by rikas** [comment]
Hi there @confile,

You mean to have a link that will send your costumer to the app store and then back to the original deep link? If that's the case than you sure can, that's what we call deferred deep linking. If you want to know more just let me know.

Cheers

**Comment by confile** [comment]
@rikas Yes that is what I want. Send the customer to the app store and the back to the deep link. 

How can I do that?

**Comment by rikas** [comment]
@confile you just have to configure your deep link and you will have that feature for free.

We have an example of that feature on the newsletter example on our landing page (http://hokolinks.com). You can even have custom parameters that you can read once the customer installs your app.
